### ISSUE TITLE
Filter x265

### ISSUE THREAD

**Issue by sheikr** [tknorris/tknorris-beta-repo#10]
This is actually a feature request. At this moment, an important number of devices can't play any hevc/x265 clips. Is it possible to add a setting to filter these from the source "picker"? Is it possible to check if the hardware can handle it?
Thanks

**Comment by tknorris** [comment]
I don't plan to do so. All my hw can play x265 and they are labelled so just don't pick them.

**Comment by sheikr** [comment]
Would you merge a PR if I coded this feature? Unlikely you, I don't have any media box that can play x265 (mostly RPis) and I'm probably the only one in my house that knows what x265 is...

**Comment by tknorris** [comment]
I'd rather not. It might be easier for you to just turn off the scrapers that can have the. They are possible in dd.tv, farda, oneclicktvshows, and tvrelease. If you set your max quality limit to 720p, then you'll never see them from dd.tv
