### ISSUE TITLE
Movietv.to scraper

### ISSUE THREAD

**Issue by fouzo14** [tknorris/tknorris-beta-repo#11]
is there going to be a fix for movietv.to scraper soon, because without out it salts is having problems pulling up the right scraper but with movietv.to i was getting the right movie in full hd every time and if you fix the scraper to fully work again then i can show you the configurations i put in salts.

p.s: i believe the movies are still on the site but they are programed to stop after five min, so if you can take of the that program or just simply pull it full from the site you might have a permanent fix. I have tested this theory many times and It has work but because i only know a little bit of coding I am limited. So I taught the best thing to do was to tell since you are in a better position to do it. 

I also want to thank very much for your hard work , trust me i know how that feels like but i just want you to keep trying hard to fix this scraper because  it is the most dependable source for movies on salts. So don't give up and keep trying and also try my idea i am pretty sure its a permanent fix.

**Comment by tknorris** [comment]
If you think you have a fix, when can I expect your pull request?

**Comment by fouzo14** [comment]
like i said, i don,t know allot about coding , i am new. but i believe the problem with the scraper is that the movies are timed to stop after 5 minutes and i thought this info could help you fix the scraper.but if you can't do it that's okay I just wanted to help. I am still very new to this.

 but I also have a list of sites you could use for salts, hope this helps you out. these are the best sites out there.

1.) http://movieshd.tv
2.)http://yify.tv
3.)http://moviesub.net
4.)http://viooz.ac
 5.)http://moviewatcher.to
