### ISSUE TITLE
"My Calendar" won't save default view.

### ISSUE THREAD

**Issue by MehBlorg** [tknorris/tknorris-beta-repo#13]
Not sure if it should. I see there is a special way to set a default view on shows and movies, but not anything else. I use My Calendar and My Next Episodes mostly, and would like to change the default view on those to tri panel (or tri list... can't recall actual name). 

Is there a way?  If not, pls consider adding one.

Thanks for all the gr8 work! Excellent add-on.

**Comment by tknorris** [comment]
if you pick the view you want for those directories while in them (via the slide out menu) they should stick.

**Comment by MehBlorg** [comment]
Tried that before opening this. They don't. :-(

FYI, I am running the Jan update of OSMC on a RPi 2, with the Aeon Nox skin.

**Comment by tknorris** [comment]
Must be a skin problem then, they stick in Confluence. I just did this myself the other day.

**Comment by MehBlorg** [comment]
OK. I will try tonight with Confluence. Thanks man.
