### ISSUE TITLE
torba.se

### ISSUE THREAD

**Issue by fouzo14** [tknorris/tknorris-beta-repo#14]
torba.se source is not workinh on salts please help

**Comment by tknorris** [comment]
Upload a log and I need more info about how it's not working.

**Comment by fouzo14** [comment]
when i play the source it asks me to scan the bar code

**Comment by tknorris** [comment]
So, did you do that?

**Comment by tknorris** [comment]
did you read the directions in the window?

**Comment by fouzo14** [comment]
i cant because i am using a computer

**Comment by tknorris** [comment]
then open another window and go to the url shown in the window

**Comment by tknorris** [comment]
or scan it w/ your phone, or open the url on your phone...there are many solutions to that problem

**Comment by fouzo14** [comment]
am going but i will be back 20 min

**Comment by fouzo14** [comment]
am back and i have a question

**Comment by fouzo14** [comment]
why did you remove movietv.to scrapper

**Comment by tknorris** [comment]
What has that got to do with your original issue? I removed it before it was broken.

**Comment by fouzo14** [comment]
oh ok

**Comment by tknorris** [comment]
Can I assume your original issue is resolved?

**Comment by fouzo14** [comment]
can you find a way around the torba.se ua block

**Comment by tknorris** [comment]
Torba works if you follow the directions in the window..

**Comment by fouzo14** [comment]
can ou explain

**Comment by tknorris** [comment]
Do what the frekaing directions say!

**Comment by fouzo14** [comment]
ok i will try it and by the way thanks for our help

**Comment by fouzo14** [comment]
your one of my favorite developers

**Comment by tknorris** [comment]
Thanks, let me know when you get it to work.
