### ISSUE TITLE
salt configuration

### ISSUE THREAD

**Issue by fouzo14** [tknorris/tknorris-beta-repo#15]
tknorris can you tell me how to best configure salts so it it will find the right and best sources for movies and tv shows

**Comment by tknorris** [comment]
Do the auto-configuration. That will configure it w/ the same settings I use.

**Comment by fouzo14** [comment]
i do that but it seems to still give me the wrong sources for some movies and tv shows

**Comment by tknorris** [comment]
If you get wrong source, read the FAQ for how to fix them.

**Comment by fouzo14** [comment]
where can i find the faq

**Comment by fouzo14** [comment]
and what setting confiqurations do you recommend

**Comment by tknorris** [comment]
https://github.com/tknorris/salts/wiki

**Comment by fouzo14** [comment]
thanks tknorris
