### ISSUE TITLE
tv show search issue 

### ISSUE THREAD

**Issue by grant2258** [tknorris/tknorris-beta-repo#19]
hi just reporting a problem with a TV show search. if you try playing "the 100 "season 3 episode 10 you can see there are strange characters where it says episode: 2014) 4 strange characters)-s03e10 it finds no tv shows obviously because of these characters can get the ascii codes if you need them

**Comment by tknorris** [comment]
A screenshot of what you mean might help.

**Comment by grant2258** [comment]
![20160411_164948](https://cloud.githubusercontent.com/assets/6128601/14433415/2bdf0e58-0006-11e6-8775-48f03e7a9e13.jpg)

there is the screenshot

**Comment by tknorris** [comment]
you probably have a bad response cached from Trakt. Every now and then it sends back the show name in another language other than English. The trakt team haven't been able to track down yet what causes it. Reset your url cache in Settings->Delete Cached Urls and it'll probably fix it.

**Comment by grant2258** [comment]
Cheers for that fixed it. I could have swore i cleared it before must have clicked keep instead of delete. I usual always reset the cache and reset the url bases when i have problems sorry for wasting your time is appreciated.
