### ISSUE TITLE
tv show source error

### ISSUE THREAD

**Issue by fouzo14** [tknorris/tknorris-beta-repo#20]
for some tv shows when i choose an episode it will give the source of another episode and then when i click another episode it gives me the source for the first episode i clicked. This is a very strange problem and i dont know wether it has to do with trakt or the metadata or maybe if its just a gglitch salts has. But this does not happen for all tv shows only some. For example. go to tv shows and search lab rats and click the one that is from disney and then go to season four and go to the bottom and click the vanishing part 2. It will give you the source of the vanishing part 1. but if you go up and click space colony then that is when it will give you the source for the vanishing part 2. So this is to help you better understand the problem. so you can go check it out yourself and can better understand how to fix it. I will leave a link of the picture cover of the show so you can easilly identify it when you search for the show lab rats. remember that this does not happen to all shows but just a few but i think it is good to fix the problem while it is small before it becomes big

![image](https://cloud.githubusercontent.com/assets/15494701/14477071/a6262588-00d9-11e6-8c4e-6c09349be368.png)

**Comment by tknorris** [comment]
https://github.com/tknorris/salts/wiki/Frequently-Asked-Questions#how-do-i-correct-the-addon-when-it-has-picked-the-wrong-sources-for-a-tv-show-movie-or-episode
