### ISSUE TITLE
True HDsources

### ISSUE THREAD

**Issue by fouzo14** [tknorris/tknorris-beta-repo#22]
these are new true hd sources for movies and tv shows that i think will really help the addon.

1.)www.freemoviesu.to/
2.)www.hdmovieswatch.net/
3.)www.watchmoviefull.com/
4.)www.whatsmag.xyz/
5.)movies4stream.com/
6.)myonlinemovies.tv/
7.)movie2k.io/
8.)cinemalive.tv/
9.)onlinemovies.is/
10.)movie-32.com/
11.)watch32movies.net/
12.)www.pinoy-hd.com/
13.)watchitvideos.net/
14.)moviego.co/
15.)movie24k.net/
16.)movie.geourdu.com/
17.)megashare.sc/
18.)www.movietubenow.biz/
19.)film-streamingx.com/
20.)watchonlinemovie.co/
21.)housemovie.to/
22.)putlocker-hd.com/
23.)www.megahd.org/
24.)www.hdmoviezone.net/
25.)onlinemoviespro.pro/
26.)www.kiwihd.com/
27.)watch5s.com/

**Comment by tknorris** [comment]
Can you remove the http from each one and make them not clickable?

**Comment by fouzo14** [comment]
ok no problem

**Comment by fouzo14** [comment]
I just did what you said is it okay now

**Comment by tknorris** [comment]
Thanks, I'll take a look at them.
