### ISSUE TITLE
SALTS ERROR

### ISSUE THREAD

**Issue by PAULAAJ2601** [tknorris/tknorris-beta-repo#23]
Hi, am getting a notification STREAM ALL THE SOURCES ERROR - SEE LOG FOR DETAILS' when using SALTS BETA and either trying to get into My Next Episodes or when an episode has finished and its trying to go back to the MNE screen (usually in the middle of running the discovering next episodes process)  Can you tell me what the problem is and how I can sort it

http://xbmclogs.com/pvpeztz7n

Many thanks

**Comment by tknorris** [comment]
It's a resource error w/ your box not able to handle the number of threads that SALTS starts to get MNE results. You need to reduce the number of shows that are in your progress list. Go to the trakt website and bring up the progress page and hide shows that you have completed or don't want to see progress for.

**Comment by PAULAAJ2601** [comment]
Ok, have done this.  But just to point out it was only happening intermittently.  It would do it and then if I tried to run again immediately after it was successful.  Surely in both these cases it would be doing exactly the same task and pulling the exact same number of results, so why play up in some instances and not others?

**Comment by tknorris** [comment]
Because your assumption is incoreect. The first time requires more resources than the second time.

**Comment by PAULAAJ2601** [comment]
Ok, thanks for your help.  Still happening intermittently even though I 
have removed progress of several series.  Not happened before even 
though had exactly the same items in list and also not happening on my 
other box which is linked to the same trakt account & lists

**Comment by tknorris** [comment]
if it continues to happen, post a new log.

**Comment by PAULAAJ2601** [comment]
Hi, still having this problem occassionally.  Haven't got a log yet but 
will send one when I can get it.  Just wanted to let you know I 
previously stated that it wasn't happening on my other box, however 
after updating that box to Jarvis 16.1 this weekend, I am now having the 
same problem.  Was previously on 14.3 and had no problem at all

**Comment by PAULAAJ2601** [comment]
Sorry logs so long, have had to just leave running until error occured


http://xbmclogs.com/pu2asydeq

**Comment by tknorris** [comment]
It's still the same problem as before. There's really nothing I can do about it. It's a resource limit on the machine preventing a new thread from being started.

**Comment by PAULAAJ2601** [comment]
Ok, just seems strange that it worked ok on both machines on older 
version of Kodi - only had the issue since the upgrade to Jarvis.

**Comment by PAULAAJ2601** [comment]
Hi, FYI have found that deleting the cached URLs stops the problem 
temporarily, obviously until it fills up again.  Just thought I'd let 
you know in case anyone else has the same problem at any time

**Comment by tknorris** [comment]
Clearing which cache fixes it?

**Comment by PAULAAJ2601** [comment]
If you go into the SALTS settings there is an option to remove cached 
url.  If I do that the problem does not occur again for a while until it 
fill up again.  It gives you a warning that removing them may slow 
things down but personally have not noticed any difference

**Comment by tknorris** [comment]
It's probably coincidence more than anything. When the cache is empty, that slows down how fast results are returned which means threads get started and ended slower. It's also possible that your drive is filling up as url's are cached.

**Comment by PAULAAJ2601** [comment]
It may of course just be pure coincidence, but it got to a stage where 
it was happening everytime it was running the discovering next episode 
process.  Both when trying to get into the MNE list and after watching a 
program and trying to return to the MNE list.  After I cleared the 
Cached URL(s) had no problem for a while

**Comment by PAULAAJ2601** [comment]
sorry it appear our last messages crossed.  Is there anyway I can stop 
my drive from filling up if this is the case, or any way I can check if 
this is what is happening?

**Comment by tknorris** [comment]
Other than just keeping as much available as possible, not really. SALTS reclaims space when it can. If it starts happening again in the future, instead of clearing the whole url cache, just delete on url (by selecting that url) and see if that helps. That triggers a "vacuum" which reclaims unused space.

**Comment by PAULAAJ2601** [comment]
Ok brill, will give that a go.  Thanks
