### ISSUE TITLE
URL Resolver query

### ISSUE THREAD

**Issue by PAULAAJ2601** [tknorris/tknorris-beta-repo#27]
Hi, I'm running the beta version of SALTS and was wondering which version of the URL resolver I should be running alongside it.  I have a vague memory of reading somewhere that if using the beta of SALTS you should use a beta of URL resolver.  I was using version 2.10.13 beta9 but it seems to have automatically updated to 3.0.5.  Reason for asking Is that i'm being kicked out of Kodi when trying to play movies as the moment and am aware that there are issues with the Url resolver currently

Thanks

**Comment by tknorris** [comment]
3.0.5 is the correct version. There are no known issues w/ URLResolver at the moment.

**Comment by Bigperm1** [comment]
Hello tknorris, 
I am having no luck getting real-debrid (urlresolver) to work on my Mac (El Capitan), It does work great in Exodus, but I cannot get it to work in urlresolver? I have tried it on Jarvis 16.0/beta 9/3.0.6, also Jarvis 16.1/Beta9/3.0.6. both Jarvis installs are fresh nothing on them but your Beta repo from Github. I have done what all the tutorials say, change priority to 90 click ok, go back in an (re)authorize but absolutely nothing. but then I'll install Exodus and it works? any help would be greatly appreciated.
Thanks
Jeff

**Comment by tknorris** [comment]
turn on debug, access a link, upload the log, post a link to the log. anything else is just guesses.

**Comment by Bigperm1** [comment]
Sorry man you lost me, i turned debug on,I accessed a movie, and now Im lost, i'm kinda new at this.

**Comment by tknorris** [comment]
https://www.tvaddons.ag/posting-error-logs-kodi/

**Comment by Bigperm1** [comment]
http://xbmclogs.com/pdkxucybp

**Comment by tknorris** [comment]
It looks to me like you don't have the RD resolver either authorized or enabled.

**Comment by Bigperm1** [comment]
I do have it enabled, and set to priority 90

**Comment by tknorris** [comment]
did you go through the authorization process?

**Comment by Bigperm1** [comment]
with real-debrid/devices? yes on all occasions, when I anter the code from urlresolver in RD Kodi says authorized but when I go back into urlresolver to double check the authorization it still says (re)authorize

**Comment by tknorris** [comment]
Yes, that's normal...go through the auth process w/ debug turned on and post that log.

**Comment by Bigperm1** [comment]
ok

**Comment by Bigperm1** [comment]
http://xbmclogs.com/pclm44hwv

**Comment by tknorris** [comment]
and if you try to get sources again, you still don't see the debrid links?

**Comment by Bigperm1** [comment]
no I don't, in salts i made sure that Debrid links are marked green.
http://xbmclogs.com/p6qwixnyq

**Comment by tknorris** [comment]
So, I know what's happening, but fixing it is another matter. Let me make some code changes and you'll have to copy them over top of the existing RD resolver and we'll see if that fixes it. Give me a few mins.

**Comment by tknorris** [comment]
OK, so since you are new, this is going to be hard for you. You need to find the file:
special://home/addons/script.module.urlresolver/lib/default.py
and replace it with this one:
http://tknorris.offshorepastebin.com/default.py

[This page]( http://kodi.wiki/view/Special_protocol) describes where special://home is.

Once you've done that, try to authorize RD again, and then get sources and see if it works now.

Let me know if it still doesn't work. What's happening is the authorization is working, but then kodi is failing to store the setting that urlresolver asks it to so it can be used later. I've seen it before, but not in a long time.

**Comment by Bigperm1** [comment]
Ok im on it

**Comment by Bigperm1** [comment]
OK i found it, when I open the existing default.py it open in xcode, do I just delete the exisiting and paste the new one in xcode?

**Comment by tknorris** [comment]
you don't need to open the existing one, just copy the new one on top of it.

**Comment by Bigperm1** [comment]
OK, so I works now, I see the (REA) files in green and I tried a couple movies and they worked. 2 off them gave a (503) error. I still don't see in urlresolver that I am authorized though? I am able to update to Jarvis 16.1? and if i get the same issue Can I replace the dafault.py file with what you gave me?

**Comment by tknorris** [comment]
Yes, you should be fine...3.0.7 of URLResolver will contain the same fix, so you don't need to keep replacing the file once you see 3.0.7 of URLResolver show up.

**Comment by Bigperm1** [comment]
Dude your AWESOME!!!! where can I donate? absolutley fantastic support....

**Comment by tknorris** [comment]
I don't really do donations. If you want to help you, you can sign up for premiumize using my referral link: https://www.premiumize.me/ref/623120054 It's another RD-like service.

**Comment by Bigperm1** [comment]
Ok cool I signed up, when my RD expires in 22 days I switch over to Premiumize.me.

Thanks again.
