### ISSUE TITLE
torba account

### ISSUE THREAD

**Issue by fouzo14** [tknorris/tknorris-beta-repo#29]
can you please put an account section for the torba.se scraper so that I can stream from my torba.se account, It is a new thing they just added.

**Comment by tknorris** [comment]
What good would having an account do?

**Comment by fouzo14** [comment]
it will alloiw you to stream from the site without having to do the authorization thing. But if you dont think it will do anything thats okay I just thought it was worth a shot

**Comment by tknorris** [comment]
I'll check on that. I don't think being authenticated allows you to avoid the ad visit thing.

**Comment by fouzo14** [comment]
I am not sure either But I just think its is worth a shot

**Comment by fouzo14** [comment]
I closed it because I just wanted you to try and see if it would work
