### ISSUE TITLE
Being kicked out of SALTS

### ISSUE THREAD

**Issue by PAULAAJ2601** [tknorris/tknorris-beta-repo#30]
Hi

have recently been experiencing a problem when using SALTS.  Doesn't happen all the time but enough so that its become a concern.  After I have selected a program that I want to watch and it is running the process of finding sources I will all of a sudden get kicked out of kodi and back onto my Android Home Screen.  I'm not quite sure how I can post a log of this as obviously once I get kicked out and go back in a new log is generated.  If you can talk me through how to obtain the 'old' log i'll do my best to post it

**Comment by tknorris** [comment]
If you use the [tva log uploader](https://www.tvaddons.ag/posting-error-logs-kodi/) there is an option in settings to include the old log.

**Comment by PAULAAJ2601** [comment]
Brill, thanks.  Will wait for it to start happening again and post log

**Comment by PAULAAJ2601** [comment]
Your kodi.old.log: https://logs.tvaddons.ag/pfwmqi9yh
Your kodi.log: https://logs.tvaddons.ag/p1prlgdz7

**Comment by tknorris** [comment]
There's not enough info in the log to see why Kodi crashed. I can isolate it down to about 50-100 lines of code but that's not close enough to make any guess as to the cause.

**Comment by tknorris** [comment]
What do you have configured under Source Management for Exclusion List and Max Qualities?

**Comment by PAULAAJ2601** [comment]
Nothing in exclusion list and max quality for both TV Show & Movies is HD1080

**Comment by tknorris** [comment]
Hmm. then there isn't much happening before urlresolver is applied, so it's probably somewhere in there. I don't see anything in the log out of the norm though.

**Comment by tknorris** [comment]
Please test 2.0.64 of SALTS. It should fix this issue.

**Comment by PAULAAJ2601** [comment]
Will do, thanks
