### ISSUE TITLE
My Next Episodes - SALTS beta

### ISSUE THREAD

**Issue by PAULAAJ2601** [tknorris/tknorris-beta-repo#33]
Hi

Am having a problem with MNE.  I should have only three shows in there (have double checked on TRAKT and there are only three showing as being on deck to watch), however there are now a load of other episodes in there.  All the episodes that are showing are from shows in my subscriptions BUT these episodes are all marked off as being watched in both SALTS & TRAKT.  Have tried again marking them as watched in SALTS but made no difference.  Don't really want to 'HIDE PROGRESS' as they are shows that are still ongoing.  At a bit of a loss, any advice please?

Regards
Paula

PS:  Have just tried running MNE of my other setup and am getting exactly the same results

**Comment by tknorris** [comment]
turn on debug and post a log. make sure to tell me which shows are incorrect.

**Comment by tknorris** [comment]
FYI, no log needed. Someone else reported the problem and provided a log. It's a trakt API issue. I'll close this issue once they fix it.

**Comment by PAULAAJ2601** [comment]
Ok thanks, did wonder as it was happening on both setups and I'd noticed on twitter that they've been doing
