### ISSUE TITLE
Fresh new sources 

### ISSUE THREAD

**Issue by fouzo14** [tknorris/tknorris-beta-repo#34]
1.)  http://cafemovie.me/
2.)  http://www.phimmoi.net/
3.)  http://movieflixter.to/
4.)  http://zoocine.com/
5.)  http://streamdreams.org/
6.)  http://www.gardenofmovies.com/
7.)  http://movierizer.com/
8.)  http://hugemoviesdb.net/
9.)  http://putlockerhd.fr/
10.) http://youmovies.tv/
11.) http://housemovie.to/
12.) https://xmovies8.org/
13.) http://tvrush.eu/
14.) http://moviesnshows.net/

**Comment by tknorris** [comment]
Thanks.
