### ISSUE TITLE
Setting to enable "extended" dialog from outside addon (ie widgets) for KRYPTON only

### ISSUE THREAD

**Issue by mastafunk** [tknorris/tknorris-beta-repo#35]
When changes were made here to get ready for Krypton you had talked about potentially adding a setting for this.

**Comment by tknorris** [comment]
Yep, it's still on the list.

**Comment by tknorris** [comment]
I added a setting for this on the source management tab. It won't show up unless you have the hidden settings enabled for now. Once Krypton comes out I'll make it visible to all.
