### ISSUE TITLE
TV Show missing Title and plot info in Library

### ISSUE THREAD

**Issue by stoelwinder** [tknorris/tknorris-beta-repo#37]
Let me start off by saying "No, this is not an incorrect scrape". I think this may be related to the title of the show.

I added "Tosh.0" (sans quotes) to my library and I can see it pulls all the episodes properly. However, when I check the library, the show appears at the top of the list, instead of the network logo, it shows the poster of the show and there's no title. Just a blank entry. When I click it, all episodes have the correct info pulled but when I press show information, title, plot, actors and everything is empty.

I think this may somehow be caused by the period in the title?

When I make the files manually, or when I pulled the data from my old Genesis streams, it displays correctly. Just doesn't when SALTS is used. All other shows (so far) display correctly.

**Comment by tknorris** [comment]
I know you said it's not an incorrect scrape, but that's precisely what it sounds like. Did you try the 2nd option listed in [this FAQ](https://github.com/tknorris/tknorris-beta-repo/wiki/SALTS---Frequently-Asked-Questions#when-using-library-integration-what-do-i-do-when-the-show-or-movie-is-scraped-into-kodi-incorrectly).

**Comment by stoelwinder** [comment]
Hi and thanks for your prompt response.

Yes, that was indeed the first thing I tried. I brought up the context menu, selected TV Show Information (where it too shows a blank title and plot summary, etc), clicked the Refresh button and selected Yes to refresh information for all episodes. There, it actually shows the correct TV Show title: Tosh.0 (2009) and after selecting it refreshes all information. Once completed, the title shows as empty in the listing.

I've tried removing the show manually from my library (choosing Manage and Remove from Library), then updating the library but once again, no title. I tried deleting all the strm files from the TVShows folder in SALTS addon_data folder and re adding it (after removing it from library) but again title is blank. Other shows in the same folder are working fine. Only Tosh.0 resolves wrongly.

If I add it from a different source (local files or Genesis) it is showing up correctly.

**Comment by tknorris** [comment]
I'm pretty sure it's a Kodi bug. I've seen that same behaviour with local files. It seems like Kodi has some issue w/ the path and then from that point forward it won't properly scan that path.

**Comment by stoelwinder** [comment]
You were indeed correct. After moving the strm files to a different folder, this particular issue went away. I'll try to follow up with the Kodi developers but since they don't want much to do with Android, that might prove to be a challenge. Thanks again for the prompt and courteous support!
