### ISSUE TITLE
[SALTS] XMovies8v2

### ISSUE THREAD

**Issue by NitroXenon** [tknorris/tknorris-beta-repo#39]
I found that you're using ```(.*?)\s+(\d{4})$``` to search for the year in the title in XMovies8v2. AFAIK the year is in brackets e.g. Deadpool (2016) and you need ```(.*?)\s+\((\d{4})\)$``` to match it.

**Comment by tknorris** [comment]
Thanks, I'll check it out. At one time they didn't include the years in parens but it looks like they've changed that.

**Comment by NitroXenon** [comment]
Yea. Ty tk. This addon is awesome!

**Comment by NitroXenon** [comment]
Btw one more thing: Stage66 and Moviezone seems to be dead?

**Comment by tknorris** [comment]
I usually leave them for a couple of weeks to see if they come back

**Comment by NitroXenon** [comment]
Alright :P
