### ISSUE TITLE
SALTS Maintenance

### ISSUE THREAD

**Issue by mygithubuserid** [tknorris/tknorris-beta-repo#42]
Hi,
Are there any maintenance tasks that can or should be done for SALTS? I've been running SALTS, using the beta repo, for almost a year and it's on a Raspberry Pi 2 so resource availability - both CPU capacity and storage space - likely need to be considered. I'm wondering if there might be a need to perhaps empty a cache or do a complete reinstall?

I should also say that I don't think performance has degraded, I'm just looking to be proactive.

Thanks for all your hard work, SALTS is the best.

**Comment by tknorris** [comment]
SALTS does the maintenance it needs as you go. The only thing you might want to consider is to trigger a vacuum on the DB to reclaim unused space. You can do this by importing an empty file into the DB in the Database tab of addon settings.
