### ISSUE TITLE
Salts error

### ISSUE THREAD

**Issue by cynical66** [tknorris/tknorris-beta-repo#48]
Good evening! Getting error on certain aspects like popular TV shows, but some movies are working. Please help!

https://logs.tvaddons.ag/pvjhghigb

**Comment by tknorris** [comment]
There's nothing interesting in that log.

**Comment by cynical66** [comment]
Damn... OK, I went to TV shows, popular, big baby theory...

And got this log...

https://logs.tvaddons.ag/puyj1imzc

Does this help?

**Comment by tknorris** [comment]
It looks like you've update your advanced settings to disable logging so there's nothing in your log. If you are going to make changes of this kind of your config you should know what they do first.

**Comment by cynical66** [comment]
Damn man, I apologize, I'm not trying to give you a hard time. I'm
completely rookie at all this. We're not allowed to have any thing but
internet here on base, so this is all I've got. I will try and follow the
directions you sent last time again to try to get a log. If I need to
donate $ to the cause I will, sorry if I came off rude to you, that wasn't
my intention.

Sgt Bentley

I will try to re send the log.

**Comment by tknorris** [comment]
The problem is you've messed with your internal Kodi settings to disable logging so no matter what logs you capture they are going to be empty. You need to reset your advanced settings.xml or remove that setting from it.

**Comment by tknorris** [comment]
And to be clear, your weren't rude and I'm not annoyed, but regardless, my point is if you make changes to your system that you don't understand, then you are going break it.

**Comment by cynical66** [comment]
I have no idea what that means... I haven't made any changes since the last
time I sent you a log, and that one worked fine. All I did was remove some
ADD-ONS like you recommended.

I don't know what I'm supposed to remove. I'm so sorry for being this dumb
at all this, I'm really trying to learn as much as I can. How do I reset
what you're asking?

Also, dead serious! If you have a PayPal account, please let me throw some
$ at you for your help! Honestly, your salts gets me they the worst days
here, and I know a few of us use it in Iraq as well.

On Oct 10, 2016 9:45 PM, "tknorris" <notifications@github.com> wrote:

The problem is you've messed with your internal Kodi settings to disable
logging so no matter what logs you capture they are going to be empty. You
need to reset your advanced settings.xml or remove that setting from it.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/tknorris/tknorris-beta-repo/issues/48#issuecomment-252812818>,
or mute the thread

**Comment by tknorris** [comment]
Here's what I suggest. Go to the FireTV App settings and do a "Reset Data" on Kodi. This will reset everything but leave Kodi installed. You'll then have to reinstall the addons & repositories you use. As it is, I think you've made enough changes that the system as it exists is going to have problems. I also still think you should upgrade to 16.1 rather than run Beta 3. Beta builds aren't meant for long term use.

**Comment by cynical66** [comment]
I saved my build the way it is on my computer. Should I restore and try to
see if that works?

**Comment by cynical66** [comment]
There's about 6 of us all using the same copy. 4 are here on base, the
other 2 are on deployment

**Comment by tknorris** [comment]
You can try to restore but it depends on whether it was broken already on your computer. To be honest, I'm not a fan of trying to restore builds. I prefer to build from scratch each time bceause of junk like this. On a side note, is there a particular reason why you are using the email address of a Box Seller?

**Comment by cynical66** [comment]
Oh no... My nickname is cynical, I created the email for communication
only. I can't send and receive communication thru my army email.

**Comment by tknorris** [comment]
Your best chance of getting it working properly is upgrade to 16.1 and do a Data Reset from FTV settings. You can then reinstall what you use otherwise there's no telling what's wrong. Someone is obviously screwing w/ the config on that box w/o knowing what they are dong.

**Comment by cynical66** [comment]
Please try and help me here man! It's really small things like this that
get us thru our day here, and especially over there where my guys are!!
Look, if I go to movies and click on in theaters it brings up a list of
movies comma but once it's done getting sources and applying Source filters
it shows movies and I can play one. But then, I can click down on now
playing and it comes up with this error message. This is all after just
resetting my box again. I'm going to try and send a lot to you, please
please please try and help me on this, please.

https://logs.tvaddons.ag/pie6nfycn

If this log didn't work, let me know... I will re load my build to back
before i changed the URL resolver from the last time.

Please man, you don't know how much this means to us here.

**Comment by tknorris** [comment]
I'm not sure what reset you did, but it wasn't a complete reset because you still have the bad advancedsettings.xml. Also, there is no "In Theaters" menu item in SALTS, so I don't know what add you are using. Like I said, I think do a data reset is your best choice.

**Comment by cynical66** [comment]
If I load the copy of my build from back when I first contacted you... When
I was able to get a log, would that have the correct settings still? Or is
it somewhere deeper than that?

On Oct 10, 2016 10:39 PM, "tknorris" <notifications@github.com> wrote:
>
> I'm not sure what reset you did, but it wasn't a complete reset because
you still have the bad advancedsettings.xml. Also, there is no "In
Theaters" menu item in SALTS, so I don't know what add you are using. Like
I said, I think do a data reset is your best choice.

**Comment by tknorris** [comment]
You can try that, but I don't know if it'll work or not.

**Comment by cynical66** [comment]
I'm trying now... Will try to post a log with the directions your gave me
just like last time...

**Comment by cynical66** [comment]
https://logs.tvaddons.ag/pwqctqbkr

**Comment by cynical66** [comment]
Please tell me that worked!

**Comment by cynical66** [comment]
I just completely removed Kodi, re installed it, and am now backing up from
the last time it worked. Any help you can offer here man would be
appreciated.

**Comment by cynical66** [comment]
This is the newest attempt at getting you a log!

https://logs.tvaddons.ag/pwqctqbkr

We're getting ready for PT this morning here, just wanted to send this
before i head out. Did this log work?

**Comment by GlenConway** [comment]
tknorris is trying to help you but you keep sending the same empty log from a beta version. You need to do two things:

- Upgrade Kodi to the latest release version
- Change the debug logging value in advancedsettings.xml so that logging is enabled.

From your log file:

- Starting Kodi (16.0-BETA3 Git:2015-12-05-85a0a13). Platform: Android ARM 32-bit
- <loglevel hide="true">-1</loglevel>
- Disabled debug logging due to GUI setting. Level -1.

At the moment your settings file says hide logging in the GUI (so you can't change it) and turn off logging. See http://kodi.wiki/view/Advancedsettings.xml#.3Cloglevel.3E for more information.

Once you've upgraded Kodi and all the addons you may find your problem goes away :-)

**Comment by cynical66** [comment]
Thank you, I will try to do both of those. I don't know how they were
changed in the first place, and I didn't know how to change them back. As
far as Kodi beta version, I will update to the reg version, I'm just
worried about how my settings and skin will react. But if it is that
important, I guess I will have to take my chances. I will do these things
today when I return from being in the field. Thanks for clarifying what
needs to be done, that's what I've been asking for.

**Comment by cynical66** [comment]
I just clicked on your link about advanced settings. I have no clue what
that means or how to change it. I guess I will have some googling to do
tonight. If there's any other way to do that you may know of, please share
it!

**Comment by tknorris** [comment]
I'm telling you, based on your responses thus far your knowledge level is not going to be enough to do all this stuff. Your best choice is just to do a full "Reset Data" on the Kodi app in the FTV settings. This will reset all Kodi stuff back to the way it was installed, and then you can easily reinstall the repositories and addons you need from fusion. There is no way we can guide you through all this stuff that's not working without you having some understanding of what these pieces mean.

**Comment by cynical66** [comment]
Fair enough sir. Thanks for being as patient as you have been with me. O
apologize for taking up your time.

On Oct 11, 2016 10:51 AM, "tknorris" <notifications@github.com> wrote:

I'm telling you, based on your responses thus far your knowledge level is
not going to be enough to do all this stuff. Your best choice is just to do
a full "Reset Data" on the Kodi app in the FTV settings. This will reset
all Kodi stuff back to the way it was installed, and then you can easily
reinstall the repositories and addons you need from fusion. There is no way
we can guide you through all this stuff that's not working without you
having some understanding of what these pieces mean.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/tknorris/tknorris-beta-repo/issues/48#issuecomment-252992604>,
or mute the thread

**Comment by tknorris** [comment]
Do you know how to do a Reset Data on the FTV?
