### ISSUE TITLE
External Search Fix?

### ISSUE THREAD

**Issue by ImReallyShiny** [tknorris/tknorris-beta-repo#50]
Is it possible for you to add support for using a Search Mode from lets say a Menu Onclick Action? If I use  `?section=Movies&mode=search` it will search it perfectly fine but will return the "Videos" library option rather then the actual results. It does see to originally show it but gets replaced with it as I see the results for about half a second.

**Comment by tknorris** [comment]
This works today if properly setup in your skin. More details here: https://forums.tvaddons.ag/tknorris-release-repository/40187-skin-salts-enthusiasts.html

**Comment by ImReallyShiny** [comment]
Im almost fully sure I set it up right - `ActiveWindow(Videos, "plugin://plugin.video.salts/?section=Movies&mode=search",return)` - This never worked for me in other skins either not even in the Default Skin (Im on v17 beta 3)

**Comment by ImReallyShiny** [comment]
http://i.imgur.com/IaI8t50.gifv
As you can see it does work for the first one you search upon loading - But then the second time it will fail to work (Seems to be some kind of cache issue possibly).

**Comment by ImReallyShiny** [comment]
If I go into settings and press random stuff to go into a few menus and go back to the main menu and search something it works again - This is very odd - Is it possible that you can try use those EndOfDirectory(Cache=False) thing or whatever? Possibly it will work then

**Comment by tknorris** [comment]
You didn't set it up right, it requires two different steps in the widget. The answer is in that thread I linked.

**Comment by ImReallyShiny** [comment]
I cant find whatever your on about anywhere in the thread D:

**Comment by tknorris** [comment]
Try this thread: https://forums.tvaddons.ag/tknorris-release-repository/27761-adding-search-function-skin.html

That's not the one I was thinking about though. The one I was thinking about was where @ashtonaut had done it with 2 steps. I don't really use widgets so I've never set it up.

**Comment by ImReallyShiny** [comment]
ActivateWindow(10025,plugin://plugin.video.salts/?mode=browse&amp;section=TV,return)
RunPlugin(plugin://plugin.video.salts/?mode=search&amp;section=TV)
So im supposed to do something like this? No idea how im meant to do both in one widget doe :/

**Comment by tknorris** [comment]
It's something like that but based on search and search_results. SALTS does a two phase transaction for searches so that the keyboard doesn't pop-up when you hit back.

**Comment by ImReallyShiny** [comment]
Do you mean this? `ActivateWindow(10025,&quot;plugin://plugin.video.salts/?query=[%SF%]&section=Movies&mode=search_results&amp;sf_fanart= special%3A%2F%2Fhome%2Faddons%5Cplugin.video.salts %5Cart%5Cthemes%5CIconic%5Cfanart.jpg_&quot;,retur n)`

**Comment by tknorris** [comment]
I don't remember exactly because I don't use widgets personally. I just know that they got it working and it required two steps in the widget action.

**Comment by tknorris** [comment]
The main point here being that search widgets can be made to work with SALTS as is. You don't need any changes from me to make it work.

**Comment by ImReallyShiny** [comment]
I understand but I just cant find a way to make it work at all D: You should just add a mode where if you do ?mode=directsearchmovie&query=Deadpool it will result the Movie and same with TV and then it will return it :/

**Comment by tknorris** [comment]
Sorry, I'm happy w/ the way it is now. I don't use widgets so a dedicated widget mode would serve no purpose for me.

**Comment by ImReallyShiny** [comment]
Alright :/

**Comment by ImReallyShiny** [comment]
Ayy - If I use RunScript() with the following script.py
```
xbmc.executebuiltin('ActivateWindow(10025, plugin://plugin.video.salts/?mode=browse&section=TV)')
xbmc.executebuiltin('RunPlugin(plugin://plugin.video.salts/?mode=search&section=TV)')
```
It will work :D
It goes to the actual Browse bit and then searches and gets the results perfectly fine.

**Comment by tknorris** [comment]
I told you it would work ;-)
