### ISSUE TITLE
Hide Date in MyNextEpisodes

### ISSUE THREAD

**Issue by ImReallyShiny** [tknorris/tknorris-beta-repo#51]
Can you make an option to hide the Date as I dont find it useful at all - Theres already one for Time so just do something similar :)

**Comment by ImReallyShiny** [comment]
Any progress on this?

**Comment by tknorris** [comment]
No, andI doubt I will. I like the Date on MNE.

**Comment by ImReallyShiny** [comment]
So just because you want the date your not making a setting to hide it?

**Comment by tknorris** [comment]
that's correct.
