### ISSUE TITLE
TV shows with apostrophes in the name aren't imported correctly

### ISSUE THREAD

**Issue by JordanLongstaff** [tknorris/tknorris-beta-repo#52]
When SALTS adds a TV show to the library with an apostrophe in the name, the apostrophe is replaced with an underscore, which prevents Kodi from scraping it correctly against TheTVDB.org. "Marvel's Agents of SHIELD" is an easily available example of this.

**Comment by tknorris** [comment]
https://github.com/tknorris/tknorris-beta-repo/wiki/SALTS---Frequently-Asked-Questions#when-using-library-integration-what-do-i-do-when-the-show-or-movie-is-scraped-into-kodi-incorrectly
