### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by gvermeiren** [tknorris/tknorris-beta-repo#57]
Suddenly I'met getting a SALTS error - "stream all the sources error check the log for more information" and won't allow me to access SALTS any longer. I am using 2.0.85

Here is my log 
https://logs.tvaddons.ag/pcsgenvf4

Thx already

**Comment by tknorris** [comment]
SuperRepo has screwed up your install. It updated my shared module to be the beta version which only works w/ the beta version of SALTS. This is why I tell people not to install such things. You need to uninstall superrpo, uninstall SALTS, uninstall tknorris.shared.module, and then reinstall SALTS.
