### ISSUE TITLE
SALTS Error - cannot open anything

### ISSUE THREAD

**Issue by arucci** [tknorris/tknorris-beta-repo#58]
Started receiving the message stream all the sources error check the log for more information yesterday and cannot view anything. 
here is the log location https://logs.tvaddons.ag/plxqvtg8z

**Comment by tknorris** [comment]
https://forums.tvaddons.ag/tknorris-release-repository/32462-stream-sources-aka-salts-v2-0-85-2016-03-30-a-131.html#post389817
