### ISSUE TITLE
icons and fanart not showing

### ISSUE THREAD

**Issue by fouzo14** [tknorris/tknorris-beta-repo#59]
can you fix the icons and fanarts not showing on the movies and tv shows. and even when it shows up it takes allot of time. i thought it was an international problem so i tried exodus but the icons worked there fine. so now i am confused because i beleive that exodus and salts both use tract tv for icon and fanart.
 hope you can help

**Comment by tknorris** [comment]
If you are using SALTS beta it should work fine.
