### ISSUE TITLE
resolver to new host: https://www.raptu.com/

### ISSUE THREAD

**Issue by antrrax** [tknorris/tknorris-beta-repo#61]
import re
import random
from lib import helpers
from urlresolver import common
from urlresolver.resolver import UrlResolver, ResolverError

class RaptuResolver(UrlResolver):
    name = "raptu.com"
    domains = ["raptu.com"]
    pattern = '(?://|\.)(raptu\.com)/(?:embed/|\?v=)?([0-9A-Za-z]+)'

    def __init__(self):
        self.net = common.Net()

    def get_media_url(self, host, media_id):
        web_url = self.get_url(host, media_id)
        headers = {'User-Agent': common.FF_USER_AGENT}
        html = self.net.http_GET(web_url, headers=headers).content
        data = helpers.get_hidden(html)
        data['confirm.y'] = random.randint(0, 120)
        data['confirm.x'] = random.randint(0, 120)
        headers['Referer'] = web_url
        post_url = web_url + '#'
        html = self.net.http_POST(post_url, form_data=data, headers=headers).content.encode('utf-8')
        sources = helpers.parse_sources_list(html)
        try: sources.sort(key=lambda x: x[0], reverse=True)
        except: pass
        return helpers.pick_source(sources)

    def get_url(self, host, media_id):
        return self._default_get_url(host, media_id, 'https://www.raptu.com/embed/{media_id}')

**Comment by tknorris** [comment]
Thanks for the resolver but someone alrady added reptu to another resolver.
