### ISSUE TITLE
artwork scraper

### ISSUE THREAD

**Issue by fouzo14** [tknorris/tknorris-beta-repo#62]
![screenshot 4](https://cloud.githubusercontent.com/assets/15494701/22267748/00261ace-e253-11e6-888d-5beab52e60c3.png)
 This is what happens when i search for something. no icon or fanart shows up. please help

**Comment by tknorris** [comment]
That is by design. I disabled artwork look ups on searches.

**Comment by fouzo14** [comment]
why, i liked that feature

**Comment by tknorris** [comment]
to improve performance.
