### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by hjanjua** [tknorris/tknorris-beta-repo#64]
I have couple of questions it's not an issue, I don't see any platform to ask this question that's why I am asking here.

1) Is there a way to any API to use this addon from other KODI addon?
2) Is there a way to call the search feature in this addon and get results to populate anywhere within KODI ?

**Comment by tknorris** [comment]
Which addon are you asking about?

**Comment by hjanjua** [comment]
SALTS, thanks

**Comment by tknorris** [comment]
On #1, not really. 
On #2, those re called skin widgets and how you do it depends on which skin you are running.
