### ISSUE TITLE
stream all the sources error: Salts

### ISSUE THREAD

**Issue by brubin10** [tknorris/tknorris-beta-repo#65]
just installed kodi 16.1, then the beast, I now get a stream all the sources error 

using V 2.0.135

have tried installing uninstalling reinstalling to no avail

1) if you need a log how can I get it (im on a firestick)
2) once I get it on firestick/tv, how do I get it online

I am tech savy with proper instructions, TYVM!!

**Comment by tknorris** [comment]
Sorry, I don't support people running builds. Also, 2.0.135 is not a current release or beta version of SALTS. If you want help, you need to install from either my beta or release repo and then post a link to your log if you still have issues.

**Comment by brubin10** [comment]
awesome quick response, can u post a link to install from release repo, tyvm

**Comment by tknorris** [comment]
It's on fusion. https://www.tvaddons.ag/addons-fusion-jarvis/

**Comment by brubin10** [comment]
ty!
