### ISSUE TITLE
Error while attempting to auto play a souece

### ISSUE THREAD

**Issue by zofer1** [tknorris/tknorris-beta-repo#67]
This is the error I get:
`23:01:56 T:1292932160   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.UnicodeDecodeError'>
                                            Error Contents: 'ascii' codec can't decode byte 0xd7 in position 3: ordinal not in range
(128)
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/plugin.video.salts/default.py", line 2769, in <module>
                                                sys.exit(main())
                                              File "/storage/.kodi/addons/plugin.video.salts/default.py", line 2760, in main
                                                url_dispatcher.dispatch(mode, queries)
                                              File "/storage/.kodi/addons/script.module.tknorris.shared/lib/url_dispatcher.py", line
 97, in dispatch
                                                self.func_registry[mode](*args, **kwargs)
                                              File "/storage/.kodi/addons/plugin.video.salts/default.py", line 1310, in get_sources
                                                auto_play_sources(hosters, video_type, trakt_id, season, episode)
                                              File "/storage/.kodi/addons/plugin.video.salts/default.py", line 1534, in auto_play_so
urces
                                                current = i18n('trying_source') % (item['quality'], item['host'], item['class'].get_
name())
                                            UnicodeDecodeError: 'ascii' codec can't decode byte 0xd7 in position 3: ordinal not in r
ange(128)
                                            -->End of Python script error report<--
2`

The fix I have for this:
Using this:
            try:
                current = i18n('trying_source') % (item['quality'], item['host'], item['class'].get_name())
            except UnicodeDecodeError:
                current = i18n('trying_source') % (item['quality'], item['host'].encode("utf-8"), item['class'].get_name())

and this:
            try:
                prev = i18n('failed_source') % (item['quality'], item['host'], item['class'].get_name())
            except UnicodeDecodeError:
                prev = i18n('failed_source') % (item['quality'], item['host'].encode("utf-8"), item['class'].get_name())

The host name comes as ascii or unicode and cannot tell when is what. There may be a more elegant solution, but this works for me.

**Comment by tknorris** [comment]
Do you know which host is coming through that way from which scraper? All the host names should be ascii...

**Comment by zofer1** [comment]
I will check and get back to you on this.

**Comment by zofer1** [comment]
Hi, I have added this code:
            try:
                current = i18n('trying_source') % (item['quality'],
item['host'], item['class'].get_name())
            except UnicodeDecodeError:
                current = i18n('trying_source') % (item['quality'],
item['host'].encode("utf-8"), item['class'].get_name())
                log_utils.log('Faulty host: (%s) quality (%s) class (%s)' %
(item['host'].encode("utf-8"),item['quality'], item['class'].get_name())
,log_utils.LOGERROR, 'play_source')


and in the log I see this:

22:48:48 T:1548743744   ERROR: Stream All The Sources: Faulty host:
(uploadx) quality (HD720) class (IceFilms)
22:48:49 T:1548743744   ERROR: URLResolver: URLError Error - From: uploadx
Link: http://uploadx.org/kevd2s1l1ws6: <urlopen error [Er
rno 1] _ssl.c:504: error:14077438:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1
alert internal error>
22:48:49 T:1548743744   ERROR: EXCEPTION Thrown (PythonToCppException) :
-->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD
TO MEMORY LEAKS!
                                            Error Type: <type
'exceptions.UnicodeDecodeError'>
                                            Error Contents: 'ascii' codec
can't decode byte 0xd7 in position 3: ordinal not in range
(128)
                                            Traceback (most recent call
last):
                                              File
"/storage/.kodi/addons/plugin.video.salts/default.py", line 2774, in
<module>
                                                sys.exit(main())
                                              File
"/storage/.kodi/addons/plugin.video.salts/default.py", line 2765, in main

url_dispatcher.dispatch(mode, queries)
                                              File
"/storage/.kodi/addons/script.module.tknorris.shared/lib/url_dispatcher.py",
line
 97, in dispatch

self.func_registry[mode](*args, **kwargs)
                                              File
"/storage/.kodi/addons/plugin.video.salts/default.py", line 1310, in
get_sources
                                                auto_play_sources(hosters,
video_type, trakt_id, season, episode)
                                              File
"/storage/.kodi/addons/plugin.video.salts/default.py", line 1547, in
auto_play_so
urces
                                                prev =
i18n('failed_source') % (item['quality'], item['host'],
item['class'].get_nam
e())
                                            UnicodeDecodeError: 'ascii'
codec can't decode byte 0xd7 in position 3: ordinal not in r
ange(128)
                                            -->End of Python script error
report<--

Please apply my workaround because with every version update I need to
apply this patch again :-(. If you like me to run any test, please send me
the code you wish to inject in the "expect" statement and I will run and
send back results.

Kindly note that I am using Hebrew for the skin, so this may have an
effect. I have little working knowledge of Python so I can't contribute
much here other than my WA and testing.

Thank you for the wonderfull work!

Zohar

**Comment by tknorris** [comment]
I don't want this fix because I want to know what's causing it first. it shouldn't be happening

**Comment by zofer1** [comment]
Most bugs are like this :-(

**Comment by zofer1** [comment]
I was trying to play Arrow, season 2 episode 19, but it happens frequently.

**Comment by tknorris** [comment]
Thanks, I'll check it out.

**Comment by tknorris** [comment]
2.0.165 should fix this issue.

**Comment by zofer1** [comment]
Can you share details about the fix you did?

**Comment by tknorris** [comment]
The fix is on line 190 of salts_utils.
