### ISSUE TITLE
Can't use thumb drive or SD card with SALTS

### ISSUE THREAD

**Issue by btthevoice** [tknorris/tknorris-beta-repo#73]
I use SALTS and EXODUS with my NEXSMART Android media center.
If I insert a thumb drive and / or SD card, I can download to them using EXODUS no problem.
But not with SALTS.
I keep getting a message "can't create download directory".
I've formatted several times and tried several different drives. 
No luck.
Hopefully you have a solution.
Thanks
Bob

**Comment by tknorris** [comment]
Try posting a log w/ debug on.

**Comment by btthevoice** [comment]
You're talking to a real greenhorn here. Can you instruct me as to how to do that please?

⁣DO NOT reply to this address !
Use 'VoiceOver@roadrunner.com'
instead please.

**Comment by tknorris** [comment]
https://www.tvaddons.ag/kodi-logs-jarvis/
