### ISSUE TITLE
is salts shutting down

### ISSUE THREAD

**Issue by fouzo14** [tknorris/tknorris-beta-repo#74]
I just heard that tv addons and zem are being sued by dish tv in a texas court and i got really worried. so i want to know if salts is going down because allot of addons have been closing after the news of the lawsuit. I use to be a coder myself and i made video and program addons also. i even had a group, i was elitetv. but i closed everything down in march because i felt something bad was going to happen and this is it. it is unclear if dish even has a basis for this lawsuit, since tv addons and zem dont make profit. but i am asking this because i like salts and i want to know if this will affect it and your personal view on this lawsuit matter. after all, we are all part of the kodi community.

**Comment by NitroXenon** [comment]
Wow closed instantly

**Comment by NitroXenon** [comment]
@fouzo14 You gotta read the news on the tvaddons forum.

**Comment by fouzo14** [comment]
i did and i am sad, i have been with kodi since the beginning and its sad to see someones tknorris's work just go down the drain, i am also a developer and i code for fun. i also made allot of addons so i can understand is tknorris is angry, because i feel the same way about the lawsuit

**Comment by NitroXenon** [comment]
I don't know about the details. Still reading some comments on reddit. Yesterday I was surprised that by tk's move too.

**Comment by NitroXenon** [comment]
By the way, thanks tk for this great addon and his contribution to the tvaddons community. Actually I'm thinking about forking SALTS and fixing those broken scrapers.

**Comment by fouzo14** [comment]
its becase its true, tv addons confirmed it and most addons by tvaddons have been shutdown. this is not some rumor , this is the real deal. so i can understand why tknorris is mad. in fact pheonix has already shut down. alll the kodi youtubers are already talking about moving to other services like stremio and android apps. but i wont give up on kodi just yet.

**Comment by tknorris** [comment]
Come on please guys, discuss this somewhere else. not in a public forum on my github. Use some sense.

**Comment by fouzo14** [comment]
sorry tknorris, its going to be okay. dont give up
